---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-gateway
  namespace: flux-system
spec:
  interval: 5m
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/infrastructure/base/gateway
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kong
  namespace: flux-system
spec:
  interval: 5m
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/infrastructure/base/kong
  prune: true
  wait: true
  dependsOn:
    - name: infra-gateway
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-tekton-operator
  namespace: flux-system
spec:
  interval: 5m
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/infrastructure/base/tekton-operator
  prune: true
  wait: true
  dependsOn:
    - name: infra-gateway
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-dev-metallb
  namespace: flux-system
spec:
  interval: 5m
  timeout: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/infrastructure/dev/metallb
  prune: true
  wait: true
