apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: 7.3.7
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 5m
  values:
    grafana.ini:
      server:
        domain: 172.20.255.2
        root_url: http://172.20.255.2/grafana
        serve_from_sub_path: true