apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: kong
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ingress
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: kong
      interval: 5m
