apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir-distributed
  namespace: mimir
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: mimir-distributed
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 5m
